apiVersion: v1
kind: ConfigMap
metadata:
    name: converter-configmap
data:
    MP3_QUEUE: "mp3"
    VIDEO_QUEUE: "video"
    MONGO_HOST: "host.minikube.internal"
    MONGO_PORT: "27017"
    RABBITMQ_HOST: "rabbitmq"
