apiVersion: v1
kind: ConfigMap
metadata:
    name: gateway-configmap
data:
    AUTH_SVC_ADDRESS: "auth:5000"
    MONGO_HOST: "host.minikube.internal"
    MONGO_PORT: "27017"
    RABBITMQ_HOST: "rabbitmq"
